version: '3.8'

services:
  crm:
    build: .
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - .:/guilherme/src/app
  database:
    image: mysql
    ports:
      - ${DB_PORT}:3306
    restart: always   
    container_name: crm_doctor
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}


    
